truncate "HadoopMigration".accuralrecord_hadoop
truncate "HadoopMigration".atmconfig_hadoop
truncate "HadoopMigration".atmintegrationrecords_hadoop
truncate "HadoopMigration".authlevel_hadoop
truncate "HadoopMigration".blacklistuser_hadoop
truncate "HadoopMigration".businessproduct_hadoop
truncate "HadoopMigration".channelbusinessproduct_hadoop
truncate "HadoopMigration".channel_hadoop
truncate "HadoopMigration".charges_hadoop
truncate "HadoopMigration".country_hadoop
truncate "HadoopMigration".creditinfodetail_hadoop
truncate "HadoopMigration".creditlimit_hadoop
truncate "HadoopMigration".currency_hadoop
truncate "HadoopMigration".depositaccural_hadoop
truncate "HadoopMigration".faq_hadoop
truncate "HadoopMigration".favourite_hadoop
truncate "HadoopMigration".insuranceproduct_hadoop
truncate "HadoopMigration".insurancesubscription_hadoop
truncate "HadoopMigration".iprsuserdetails_hadoop
truncate "HadoopMigration".loanaccural_hadoop
truncate "HadoopMigration".loanbucket_hadoop
truncate "HadoopMigration".loan_hadoop
truncate "HadoopMigration".loanproduct_hadoop
truncate "HadoopMigration".loanschedule_hadoop
truncate "HadoopMigration".moduletransaction_hadoop
truncate "HadoopMigration".occupation_hadoop
truncate "HadoopMigration".offerbusinessproduct_hadoop
truncate "HadoopMigration".offertype_hadoop
truncate "HadoopMigration".rdproductassociation_hadoop
truncate "HadoopMigration".rdproduct_hadoop
truncate "HadoopMigration".referraloffer_hadoop
truncate "HadoopMigration".role_hadoop
truncate "HadoopMigration".rolespecialfield_hadoop
truncate "HadoopMigration".rolewalletsetting_hadoop
truncate "HadoopMigration".safaricomcustomercreditscoredetails_hadoop
truncate "HadoopMigration".specialfield_hadoop
truncate "HadoopMigration".userenhancekyc_hadoop
truncate "HadoopMigration".userkycdetails_hadoop
truncate "HadoopMigration".userkyc_hadoop
truncate "HadoopMigration".userreferral_hadoop
truncate "HadoopMigration".users_hadoop
truncate "HadoopMigration".walletbalance_hadoop
truncate "HadoopMigration".wallettype_hadoop
truncate "HadoopMigration".creditlimitpending_hadoop
truncate "HadoopMigration".atmconfigaudit_hadoop
truncate "HadoopMigration".authlevelaudit_hadoop
truncate "HadoopMigration".businessproductaudit_hadoop
truncate "HadoopMigration".channelaudit_hadoop
truncate "HadoopMigration".chargesaudit_hadoop
truncate "HadoopMigration".coaaudit_hadoop
truncate "HadoopMigration".currencyaudit_hadoop
truncate "HadoopMigration".faqaudit_hadoop
truncate "HadoopMigration".favouriteaudit_hadoop
truncate "HadoopMigration".offertypeaudit_hadoop
truncate "HadoopMigration".truncatereferralofferaudit_hadoop
truncate "HadoopMigration".roleaudit_hadoop
truncate "HadoopMigration".rolewalletsettingaudit_hadoop
truncate "HadoopMigration".specialfieldaudit_hadoop
truncate "HadoopMigration".userenhancekycaudit_hadoop
truncate "HadoopMigration".usersaudit_hadoop
truncate "HadoopMigration".wallettypeaudit_hadoop
