INSERT INTO "HadoopMigration".businessproduct_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, bpcode, name, description, fromwallettype, towallettype, fixeddestination, enabled, onlywithinhierarchy, authrequired, destinationuserid, minamountpertrx, maxamountpertrx, maxamountperweekcredit, maxamountpermonthcredit, maxamountperdaycredit, maxcountperweekcredit, maxcountpermonthcredit, maxcountperdaycredit, maxamountperweekdebit, maxamountpermonthdebit, maxamountperdaydebit, maxcountperweekdebit, maxcountpermonthdebit, maxcountperdaydebit, image, integrationclass, denominationjson, category) 
SELECT nextval('businessproduct_seq'), id, createdby, createdon, modifiedby, modifiedon, bpcode, name, description, fromwallettype, towallettype, fixeddestination, enabled, onlywithinhierarchy, authrequired, destinationuserid, minamountpertrx, maxamountpertrx, maxamountperweekcredit, maxamountpermonthcredit, maxamountperdaycredit, maxcountperweekcredit, maxcountpermonthcredit, maxcountperdaycredit, maxamountperweekdebit, maxamountpermonthdebit, maxamountperdaydebit, maxcountperweekdebit, maxcountpermonthdebit, maxcountperdaydebit, image, integrationclass, denominationjson, category
FROM public.businessproduct;

INSERT INTO "HadoopMigration".channel_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, name, description, key, authenticationrequired) 
SELECT nextval('channel_seq'), id, createdby, createdon, modifiedby, modifiedon, name, description, key, authenticationrequired
FROM public.channel;

INSERT INTO "HadoopMigration".charges_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, name, description, masterbpid, sourcewallettype, destinationwallettype, fixedsourcewallet, fixeddestinationwallet, enabled, applicabilityjson, approvalstatus, remarks, statuschangedby, statuschangedon, fromchargetype, tochargetype, banner, fixedsourceusername, fixeddestinationusername) 
SELECT nextval('charges_seq'), id, createdby, createdon, modifiedby, modifiedon, name, description, masterbpid, sourcewallettype, destinationwallettype, fixedsourcewallet, fixeddestinationwallet, enabled, applicabilityjson, approvalstatus, remarks, statuschangedby, statuschangedon, fromchargetype, tochargetype, banner, fixedsourceusername, fixeddestinationusername
FROM public.charges;

INSERT INTO "HadoopMigration".coa_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, name, description, coacode, parentid, creditamount, debitamount, reservedcreditamount, reserveddebitamount, amountupdatedon, currencyid, superparentid) 
SELECT nextval('coa_seq'), id, createdby, createdon, modifiedby, modifiedon, name, description, coacode, parentid, creditamount, debitamount, reservedcreditamount, reserveddebitamount, amountupdatedon, currencyid, superparentid
FROM public.coa;

INSERT INTO "HadoopMigration".currency_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, name, description, pattern, symbol, currencytype, code) 
SELECT nextval('currency_seq'), id, createdby, createdon, modifiedby, modifiedon, name, description, pattern, symbol, currencytype, code
FROM public.currency;

INSERT INTO "HadoopMigration".favourite_hadoop(sequenceid, id, bpcode, amount, fromusername, tousername, speicalfieldvaluesjson, ownerid, transactiontype, createdon, beneficiaryname, favtype, accountnumber, billername) 
SELECT nextval('favourite_seq'), id, bpcode, amount, fromusername, tousername, speicalfieldvaluesjson, ownerid, transactiontype, createdon, beneficiaryname, favtype, accountnumber, billername
FROM public.favourite;

INSERT INTO "HadoopMigration".offertype_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, name, description, image, category, enabled, applicabilityjson, businessidsjson, promocodeapplicable, percentageoff, valueforoffer, maxamountcap, payeraccount, receiver, disbursementafterdays, validfrom, validtill, offertyperemarks,  code, codetype, maxusagecount, redeemtioncount, computationtype) 
SELECT nextval('offertype_seq'), id, createdby, createdon, modifiedby, modifiedon, name, description, image, category, enabled, applicabilityjson, businessidsjson, promocodeapplicable, percentageoff, valueforoffer, maxamountcap, payeraccount, receiver, disbursementafterdays, validfrom, validtill, offertyperemarks,  code, codetype, maxusagecount, redeemtioncount, computationtype
FROM public.offertype;

INSERT INTO "HadoopMigration".role_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, name, description, roletype, validateemail, forbidobviouspassword, forcechangefirstpassword, numbersrequired, charactersrequired, specialcharactersrequired, capitalrequired, maxwrongpasswordallowed, passwordexpirydays, deactivatepasswordminutes, reusepasswordafter, enabled, minpasswordlength, maxpasswordlength, tokenexpiryminutes, dormantafterdays, closeafterdays, authoritylevel, agreement, documenttypejson, upgradable, updatetogroup, subtype, userstatus, delaytimetousetxminutes, notallowedbpindelaytimejson) 
SELECT nextval('role_seq'), id, createdby, createdon, modifiedby, modifiedon, name, description, roletype, validateemail, forbidobviouspassword, forcechangefirstpassword, numbersrequired, charactersrequired, specialcharactersrequired, capitalrequired, maxwrongpasswordallowed, passwordexpirydays, deactivatepasswordminutes, reusepasswordafter, enabled, minpasswordlength, maxpasswordlength, tokenexpiryminutes, dormantafterdays, closeafterdays, authoritylevel, agreement, documenttypejson, upgradable, updatetogroup, subtype, userstatus, delaytimetousetxminutes, notallowedbpindelaytimejson
FROM public.role;

INSERT INTO "HadoopMigration".rolewalletsetting_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, roleid, wallettypeid, creditlimit, debitlimit, minimumbalance, dailymaxdebitamount, dailymaxcreditamount, dailymaxtotalamount, dailymaxcreditcount, dailymaxdebitcount, dailymaxtotalcount, weeklymaxdebitamount, weeklymaxcreditamount, weeklymaxtotalamount, weeklymaxcreditcount, weeklymaxdebitcount, weeklymaxtotalcount, monthlymaxdebitamount, monthlymaxcreditamount, monthlymaxtotalamount, monthlymaxcreditcount, monthlymaxdebitcount, monthlymaxtotalcount, description, needssettlement, settlementinterval, settlementaccountid) 
SELECT nextval('rolewalletsetting_seq'), id, createdby, createdon, modifiedby, modifiedon, roleid, wallettypeid, creditlimit, debitlimit, minimumbalance, dailymaxdebitamount, dailymaxcreditamount, dailymaxtotalamount, dailymaxcreditcount, dailymaxdebitcount, dailymaxtotalcount, weeklymaxdebitamount, weeklymaxcreditamount, weeklymaxtotalamount, weeklymaxcreditcount, weeklymaxdebitcount, weeklymaxtotalcount, monthlymaxdebitamount, monthlymaxcreditamount, monthlymaxtotalamount, monthlymaxcreditcount, monthlymaxdebitcount, monthlymaxtotalcount, description, needssettlement, settlementinterval, settlementaccountid
FROM public.rolewalletsetting;

INSERT INTO "HadoopMigration".userkyc_hadoop(sequenceid, id, userid, createdby, createdon, kycdocumenttype, expirydate, kycprooftype, lastmodifedon) 
SELECT nextval('userkyc_seq'), id, userid, createdby, createdon, kycdocumenttype, expirydate, kycprooftype, lastmodifedon
FROM public.userkyc;

INSERT INTO "HadoopMigration".users_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, firstname, middlename, lastname, email, address, city, state, country, pincode, countrycode, gender, dob, roleid, username, passwordexpirydate, lastlogin, mobilenumber, roletype, parentuserid, userstatus, employeeid, emailvalidated, mobilenumbervalidated, deviceid, speicalfieldvaluesjson, agreementaccepted, sharecommission, computationtype, remarks, value, profilepicture, kycstatus, ldapuser, securityquestionjson, nationalid, referralcode, activated, biometricenabled, nontransactionnotificationallowed, idtype, idnumber) 
SELECT nextval('users_seq'), id, createdby, createdon, modifiedby, modifiedon, firstname, middlename, lastname, email, address, city, state, country, pincode, countrycode, gender, dob, roleid, username, passwordexpirydate, lastlogin, mobilenumber, roletype, parentuserid, userstatus, employeeid, emailvalidated, mobilenumbervalidated, deviceid, speicalfieldvaluesjson, agreementaccepted, sharecommission, computationtype, remarks, value, profilepicture, kycstatus, ldapuser, securityquestionjson, nationalid, referralcode, activated, biometricenabled, nontransactionnotificationallowed, idtype, idnumber
FROM public.users;

INSERT INTO "HadoopMigration".walletbalance_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, transactiontime, producttype, instancetype, walletstatus, currencyid, ownerid, creditamount, debitamount, totalbalance, reservebalance,  maxcreditamountlimit, maxdebitamountlimit, uppertotalbalancelimit, lowertotalbalancelimit, dailymaxdebitamount, dailymaxcreditamount, dailymaxtotalamount, dailymaxcreditcount, dailymaxdebitcount, dailymaxtotalcount, weeklymaxdebitamount, weeklymaxcreditamount, weeklymaxtotalamount, weeklymaxcreditcount, weeklymaxdebitcount, weeklymaxtotalcount, monthlymaxdebitamount, monthlymaxcreditamount, monthlymaxtotalamount, monthlymaxcreditcount, monthlymaxdebitcount, monthlymaxtotalcount, isactive, needssettlement, settlementinterval, settlementaccountid) 
SELECT nextval('walletbalance_seq'), id, createdby, createdon, modifiedby, modifiedon, transactiontime, producttype, instancetype, walletstatus, currencyid, ownerid, creditamount, debitamount, totalbalance, reservebalance,  maxcreditamountlimit, maxdebitamountlimit, uppertotalbalancelimit, lowertotalbalancelimit, dailymaxdebitamount, dailymaxcreditamount, dailymaxtotalamount, dailymaxcreditcount, dailymaxdebitcount, dailymaxtotalcount, weeklymaxdebitamount, weeklymaxcreditamount, weeklymaxtotalamount, weeklymaxcreditcount, weeklymaxdebitcount, weeklymaxtotalcount, monthlymaxdebitamount, monthlymaxcreditamount, monthlymaxtotalamount, monthlymaxcreditcount, monthlymaxdebitcount, monthlymaxtotalcount, isactive, needssettlement, settlementinterval, settlementaccountid
FROM public.walletbalance;

INSERT INTO "HadoopMigration".wallettransactions_hadoop(sequenceid, id, createdon, modifiedon, businesstrxid, fromortouserid, businessproductid, transactionstatus, description, parentid, source, chargebackbyid, chargebackofid, executionid, authuserid, maxauthlevel, txtime, specialfieldjson, pairid, channelid, settlementstatus, settlementerror, settlementtimestamp, settlmentaftertime, settlementjobid, remarks) 
SELECT nextval('wallettransactions_seq'), id, createdon, modifiedon, businesstrxid, fromortouserid, businessproductid, transactionstatus, description, parentid, source, chargebackbyid, chargebackofid, executionid, authuserid, maxauthlevel, txtime, specialfieldjson, pairid, channelid, settlementstatus, settlementerror, settlementtimestamp, settlmentaftertime, settlementjobid, remarks
FROM public.wallettransactions;

INSERT INTO "HadoopMigration".wallettype_hadoop(sequenceid, id, createdby, createdon, modifiedby, modifiedon, name, name_key, currencyid, description, wallettype, internalwallet, parentglid, glid, walletcode, upperlimit, lowerlimit) 
SELECT nextval('wallettype_seq'), id, createdby, createdon, modifiedby, modifiedon, name, name_key, currencyid, description, wallettype, internalwallet, parentglid, glid, walletcode, upperlimit, lowerlimit
FROM public.wallettype;

